export const ErrorCodes = {
  IMPLEMENTATION_ERROR: 'IMPLEMENTATION_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  COMPLEX_QUERY: 'COMPLEX_QUERY',
  INPUT_VALIDATION_ERROR: 'INPUT_VALIDATION_ERROR',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  ELASTIC_ERROR: 'ELASTIC_ERROR',
}
